Previous manuscripts
stefan-nistor/romanian-script-decipher pull request #27
Opened 2023-12-10 10:50 UTC by BalteanuAndrei709

2023-12-11 17:42 UTC, stefan-nistor requested changes

2023-12-11 17:42 UTC, stefan-nistor commented on Backend/src/main/java/ro/uaic/info/romandec/repository/ManuscriptRepository.java
>      Manuscript getManuscriptByPathToImage(String pathToOriginalImage);
Change the return type to `Optional<Mannuscript>`

2023-12-11 17:42 UTC, stefan-nistor commented on Backend/src/main/java/ro/uaic/info/romandec/services/ManuscriptService.java
> +    }
Maybe refactor this to reuse the code
```suggestion
    private String getDecipheredTranscriptFilename(String filename) {
    String filenameWithoutExtension = extractFilenameWithoutExtension(filename);
    return filenameWithoutExtension + ".txt";
}
```

2023-12-11 17:42 UTC, stefan-nistor commented on Backend/src/main/java/ro/uaic/info/romandec/services/ManuscriptService.java
> +    }
Maybe make use of Java Paths
```suggestion
    private String extractFilenameWithoutExtension(String filename) {
    Path path = Paths.get(filename);
    return path.getName(path.getNameCount() - 1).toString();
}
```

2023-12-11 17:42 UTC, stefan-nistor commented on Backend/src/main/java/ro/uaic/info/romandec/services/ManuscriptService.java
> +        return manuscript.get();
```suggestion
        return manuscriptRepository.getManuscriptByIdAndNameAndUserId(
                request.getManuscriptId(),
                request.getName(),
                userId).orElseThrow(() -> new NoAvailableDataForGivenInput("No manuscript found for id:" + request.getManuscriptId()));
```

2023-12-11 17:42 UTC, stefan-nistor commented on Backend/src/main/java/ro/uaic/info/romandec/controllers/ProfileController.java
You should remove try-catch blocks from Controller layer. The exception handling should take place in the Service layer. The thrown exceptions are handled in ExceptionHandlerAdvice

2023-12-11 17:42 UTC, stefan-nistor commented on Backend/src/main/java/ro/uaic/info/romandec/services/ManuscriptService.java
> +    }
```suggestion
    public List<ManuscriptPreviewResponse> getAllUsersManuscripts(UUID userId)
        throws NoAvailableDataForGivenInput {
    List<Manuscript> usersManuscripts = manuscriptRepository.getAllByUserId(userId);

    if (usersManuscripts == null) {
        throw new NoAvailableDataForGivenInput("No available manuscripts for this user.");
    }

    return usersManuscripts.stream()
            .map(m -> ManuscriptPreviewResponse.builder()
                    .manuscriptId(m.getId())
                    .name(m.getName())
                    .build())
            .collect(Collectors.toList());
}
```

2023-12-11 17:42 UTC, stefan-nistor commented on Backend/src/main/java/ro/uaic/info/romandec/services/ManuscriptService.java
> +    }
You can extract some methods to improve code readability and reduce cognitive complexity

```suggestion
    public void saveAnnotatorDecipheredManuscript(String originalImageFilename, String decipheredText)
        throws InvalidDataException, IOException {
    String filenameWithoutExtension = extractFilenameWithoutExtension(originalImageFilename);
    Path imageDirectory = Paths.get(databaseDirectory, filenameWithoutExtension);

    verifyImageDirectory(imageDirectory);

    Path filePath = resolveFilePath(imageDirectory, originalImageFilename);
    updateManuscript(imageDirectory, originalImageFilename, filePath);
    Files.writeString(filePath, decipheredText, StandardOpenOption.CREATE, StandardOpenOption.APPEND);
}

private void verifyImageDirectory(Path imageDirectory) throws InvalidDataException {
    if (!Files.exists(imageDirectory)) {
        throw new InvalidDataException("This image does not a directory associated");
    }
}

private Path resolveFilePath(Path imageDirectory, String originalImageFilename) {
    return imageDirectory.resolve(Objects.requireNonNull(getDecipheredTranscriptFilename(originalImageFilename)));
}

private void updateManuscript(Path imageDirectory, String originalImageFilename, Path filePath) {
    Path imageCompletePath = imageDirectory.resolve(originalImageFilename);
    Manuscript manuscript = manuscriptRepository.getManuscriptByPathToImage(imageCompletePath.toAbsolutePath().toString());
    manuscript.setPathToDecipheredText(filePath.toAbsolutePath().toString());
    manuscriptRepository.save(manuscript);
}
```

2023-12-13 23:11 UTC, stefan-nistor requested changes

2023-12-13 23:11 UTC, stefan-nistor commented on Backend/src/main/java/ro/uaic/info/romandec/repository/ManuscriptRepository.java
>  public interface ManuscriptRepository extends JpaRepository<Manuscript,Integer> {
Annotate with `@Repository`
```suggestion
@Repository
public interface ManuscriptRepository extends JpaRepository<Manuscript,Integer> {
```

2023-12-13 23:45 UTC, stefan-nistor commented on Backend/src/main/java/ro/uaic/info/romandec/repository/ManuscriptRepository.java
>  public interface ManuscriptRepository extends JpaRepository<Manuscript,Integer> {
Please annotate with `@Repository`
```suggestion
@Repository
public interface ManuscriptRepository extends JpaRepository<Manuscript,Integer> {
```

2023-12-13 23:51 UTC, stefan-nistor requested changes
Some changes are needed regarding ExceptionHandling. We should not extend directly `Exception` class. Made a new branch for diff checking - a5406c4

2024-01-06 18:12 UTC, stefan-nistor approved these changes

2024-01-06 18:21 UTC, StefanRoman1 approved these changes

2024-01-06 18:22 UTC, merged